server:
  port: 8083

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    #    url: jdbc:h2:file:~/test
    username: sa
    password: password
    driver-class-name: org.h2.Driver
